import type { AppState, Customer, PurchaseOrder, ReturnOrder, SalesOrder, StockReservation, Vendor, BarcodeRecord, Lot, PickingOrder, ProductExtension, SerialNumber, WarehouseZone, CycleCount, Package, Shipment, PutawayRule, LocationExtension, ProductVariant } from '../types'
import { uid } from './utils'

const DEMO_HASH =
  'ff96673205dc722320598ebf8f88325b2ac56922d5a2164b5765868274bc0d73'

export function createSeed(): AppState {
  const userId = 'usr_demo'
  const catRaw = 'cat_raw'
  const catFin = 'cat_fin'
  const catComp = 'cat_comp'

  const wh1 = 'wh_main'
  const wh2 = 'wh_two'

  const locMain = 'loc_main_stock'
  const locProd = 'loc_prod'
  const locIn = 'loc_in'
  const locOut = 'loc_out'
  const locWh2 = 'loc_wh2_stock'
  const locVendor = 'loc_vendor'
  const locCustomer = 'loc_customer'
  const locLoss = 'loc_loss'

  const vnd1 = 'vnd_metals_plus'
  const vnd2 = 'vnd_rodworks'
  const vnd3 = 'vnd_ergocomp'

  const cust1 = 'cust_northwind'
  const cust2 = 'cust_cityoffice'
  const cust3 = 'cust_apexstudio'

  const pSteel = 'prd_steel'
  const pRod = 'prd_rod'
  const pChair = 'prd_chair'
  const pFrame = 'prd_frame'

  const rec1 = 'doc_rec_1'
  const int1 = 'doc_int_1'
  const del1 = 'doc_del_1'
  const adj1 = 'doc_adj_1'

  const po1 = 'po_1'
  const po2 = 'po_2'
  const po3 = 'po_3'
  const po4 = 'po_4'

  const so1 = 'so_1'
  const so2 = 'so_2'
  const so3 = 'so_3'
  const so4 = 'so_4'

  const vendors: Vendor[] = [
    {
      id: vnd1,
      code: 'VND-001',
      companyName: 'MetalsPlus Industries',
      contactPerson: 'Robert Vance',
      email: 'orders@metalsplus.com',
      phone: '+1 555-0192',
      address: '45 Foundry Street, Pittsburgh, PA',
      taxNumber: 'US-TX-99214',
      paymentTerms: 'Net 30',
      leadTime: 5,
      status: 'active',
      notes: 'Primary bulk raw steel & extruded metal partner. Excellent reliability.',
      createdAt: '2026-09-01T08:00:00.000Z',
      updatedAt: '2026-09-20T10:00:00.000Z',
    },
    {
      id: vnd2,
      code: 'VND-002',
      companyName: 'RodWorks Precision Co.',
      contactPerson: 'Sarah Jenkins',
      email: 'sales@rodworks.io',
      phone: '+1 555-0144',
      address: '88 Mill Way, Cleveland, OH',
      taxNumber: 'US-TX-88319',
      paymentTerms: 'Net 15',
      leadTime: 7,
      status: 'active',
      notes: 'Precision mechanical rods, fasteners, and calibrated tubing.',
      createdAt: '2026-09-05T09:30:00.000Z',
      updatedAt: '2026-09-22T14:15:00.000Z',
    },
    {
      id: vnd3,
      code: 'VND-003',
      companyName: 'Ergonomic Components Ltd',
      contactPerson: 'David Chen',
      email: 'contact@ergocomp.com',
      phone: '+1 555-0188',
      address: '12 Tech Park Avenue, San Jose, CA',
      taxNumber: 'US-TX-44120',
      paymentTerms: 'Immediate',
      leadTime: 10,
      status: 'active',
      notes: 'Chair hydraulics, castors, lumbar mesh, and sub-assemblies.',
      createdAt: '2026-09-10T11:00:00.000Z',
      updatedAt: '2026-09-24T16:00:00.000Z',
    },
  ]

  const customers: Customer[] = [
    {
      id: cust1,
      code: 'CUST-001',
      name: 'Northwind Manufacturing',
      email: 'procurement@northwind.com',
      phone: '+1 555-0211',
      address: '100 Commercial Blvd, Chicago, IL',
      taxNumber: 'US-GST-10293',
      status: 'active',
      notes: 'Tier 1 client. High volume monthly production schedules.',
      createdAt: '2026-09-02T10:00:00.000Z',
      updatedAt: '2026-09-22T11:00:00.000Z',
    },
    {
      id: cust2,
      code: 'CUST-002',
      name: 'City Office Fitouts',
      email: 'ops@cityoffice.design',
      phone: '+1 555-0299',
      address: '340 Market Street, Suite 400, San Francisco, CA',
      taxNumber: 'US-GST-55412',
      status: 'active',
      notes: 'Commercial interior architectural contractor. Regular bulk furniture orders.',
      createdAt: '2026-09-08T14:20:00.000Z',
      updatedAt: '2026-09-25T09:30:00.000Z',
    },
    {
      id: cust3,
      code: 'CUST-003',
      name: 'Apex Studio Spaces',
      email: 'billing@apexstudio.net',
      phone: '+1 555-0377',
      address: '78 Broadway, New York, NY',
      taxNumber: 'US-GST-77110',
      status: 'active',
      notes: 'Co-working workspace franchise.',
      createdAt: '2026-09-12T16:45:00.000Z',
      updatedAt: '2026-09-26T08:00:00.000Z',
    },
  ]

  const purchaseOrders: PurchaseOrder[] = [
    {
      id: po1,
      number: 'PO/00001',
      vendorId: vnd1,
      warehouseId: wh1,
      orderDate: '2026-09-15',
      expectedDeliveryDate: '2026-09-20',
      status: 'received',
      currency: 'USD',
      notes: 'Initial production steel batch. Received in full.',
      lines: [
        {
          id: uid('pol'),
          productId: pSteel,
          orderedQty: 100,
          receivedQty: 100,
          unitCost: 28,
          taxRate: 10,
          subtotal: 2800,
          tax: 280,
          total: 3080,
        },
      ],
      subtotal: 2800,
      tax: 280,
      total: 3080,
      allowOverReceipt: false,
      createdAt: '2026-09-15T09:00:00.000Z',
      updatedAt: '2026-09-20T09:12:00.000Z',
      receivedDocIds: [rec1],
    },
    {
      id: po2,
      number: 'PO/00002',
      vendorId: vnd2,
      warehouseId: wh1,
      orderDate: '2026-09-18',
      expectedDeliveryDate: '2026-09-25',
      status: 'partial',
      currency: 'USD',
      notes: '50 units 10mm rods. Partial delivery of 25 units arrived on Sept 24.',
      lines: [
        {
          id: uid('pol'),
          productId: pRod,
          orderedQty: 50,
          receivedQty: 25,
          unitCost: 14,
          taxRate: 10,
          subtotal: 700,
          tax: 70,
          total: 770,
        },
      ],
      subtotal: 700,
      tax: 70,
      total: 770,
      allowOverReceipt: false,
      createdAt: '2026-09-18T10:30:00.000Z',
      updatedAt: '2026-09-24T11:00:00.000Z',
    },
    {
      id: po3,
      number: 'PO/00003',
      vendorId: vnd3,
      warehouseId: wh1,
      orderDate: '2026-09-22',
      expectedDeliveryDate: '2026-10-02',
      status: 'sent',
      currency: 'USD',
      notes: 'Ergonomic components kit for upcoming Q4 chair assembly run.',
      lines: [
        {
          id: uid('pol'),
          productId: pChair,
          orderedQty: 20,
          receivedQty: 0,
          unitCost: 85,
          taxRate: 10,
          subtotal: 1700,
          tax: 170,
          total: 1870,
        },
      ],
      subtotal: 1700,
      tax: 170,
      total: 1870,
      allowOverReceipt: false,
      createdAt: '2026-09-22T13:00:00.000Z',
      updatedAt: '2026-09-23T09:00:00.000Z',
    },
    {
      id: po4,
      number: 'PO/00004',
      vendorId: vnd1,
      warehouseId: wh1,
      orderDate: '2026-09-26',
      expectedDeliveryDate: '2026-10-01',
      status: 'draft',
      currency: 'USD',
      notes: 'Draft restock purchase order for raw steel.',
      lines: [
        {
          id: uid('pol'),
          productId: pSteel,
          orderedQty: 60,
          receivedQty: 0,
          unitCost: 28,
          taxRate: 10,
          subtotal: 1680,
          tax: 168,
          total: 1848,
        },
      ],
      subtotal: 1680,
      tax: 168,
      total: 1848,
      allowOverReceipt: false,
      createdAt: '2026-09-26T09:00:00.000Z',
      updatedAt: '2026-09-26T09:00:00.000Z',
    },
  ]

  const salesOrders: SalesOrder[] = [
    {
      id: so1,
      number: 'SO/00001',
      customerId: cust1,
      warehouseId: wh1,
      orderDate: '2026-09-18',
      deliveryDate: '2026-09-22',
      status: 'delivered',
      currency: 'USD',
      notes: 'Customer rush order fulfilled and delivered.',
      lines: [
        {
          id: uid('sol'),
          productId: pSteel,
          qty: 20,
          unitPrice: 45,
          discount: 0,
          taxRate: 8,
          subtotal: 900,
          tax: 72,
          total: 972,
        },
      ],
      subtotal: 900,
      tax: 72,
      total: 972,
      createdAt: '2026-09-18T14:00:00.000Z',
      updatedAt: '2026-09-22T14:00:00.000Z',
      deliveryDocId: del1,
    },
    {
      id: so2,
      number: 'SO/00002',
      customerId: cust2,
      warehouseId: wh1,
      orderDate: '2026-09-24',
      deliveryDate: '2026-09-28',
      status: 'reserved',
      currency: 'USD',
      notes: '4 office chairs reserved in Main Store for City Office Fitouts.',
      lines: [
        {
          id: uid('sol'),
          productId: pChair,
          qty: 4,
          unitPrice: 175,
          discount: 5,
          taxRate: 8,
          subtotal: 665,
          tax: 53.2,
          total: 718.2,
        },
      ],
      subtotal: 665,
      tax: 53.2,
      total: 718.2,
      createdAt: '2026-09-24T10:15:00.000Z',
      updatedAt: '2026-09-24T10:20:00.000Z',
    },
    {
      id: so3,
      number: 'SO/00003',
      customerId: cust3,
      warehouseId: wh1,
      orderDate: '2026-09-25',
      deliveryDate: '2026-09-29',
      status: 'confirmed',
      currency: 'USD',
      notes: 'Confirmed by client, pending inventory reservation.',
      lines: [
        {
          id: uid('sol'),
          productId: pChair,
          qty: 2,
          unitPrice: 175,
          discount: 0,
          taxRate: 8,
          subtotal: 350,
          tax: 28,
          total: 378,
        },
      ],
      subtotal: 350,
      tax: 28,
      total: 378,
      createdAt: '2026-09-25T11:00:00.000Z',
      updatedAt: '2026-09-25T11:05:00.000Z',
    },
    {
      id: so4,
      number: 'SO/00004',
      customerId: cust1,
      warehouseId: wh1,
      orderDate: '2026-09-26',
      deliveryDate: '2026-10-03',
      status: 'draft',
      currency: 'USD',
      notes: 'Draft quotation for welded steel frames.',
      lines: [
        {
          id: uid('sol'),
          productId: pFrame,
          qty: 8,
          unitPrice: 79,
          discount: 10,
          taxRate: 8,
          subtotal: 568.8,
          tax: 45.5,
          total: 614.3,
        },
      ],
      subtotal: 568.8,
      tax: 45.5,
      total: 614.3,
      createdAt: '2026-09-26T09:30:00.000Z',
      updatedAt: '2026-09-26T09:30:00.000Z',
    },
  ]

  const reservations: StockReservation[] = [
    {
      id: uid('res'),
      salesOrderId: so2,
      productId: pChair,
      warehouseId: wh1,
      qty: 4,
      createdAt: '2026-09-24T10:20:00.000Z',
    },
  ]

  const returnOrders: ReturnOrder[] = [
    {
      id: 'ret_cust_1',
      number: 'RET-C/00001',
      type: 'customer',
      status: 'completed',
      partnerId: cust2,
      partnerName: 'City Office Fitouts',
      referenceDocNumber: 'SO/00001',
      warehouseId: wh1,
      lines: [
        {
          id: uid('retl'),
          productId: pSteel,
          qty: 2,
          reason: 'Excess length ordered by site team',
          destination: 'restock',
          inspectedQty: 2,
          disposition: 'restock',
        },
      ],
      notes: 'Customer returned 2 kg unused steel; inspected and returned to Main Store.',
      createdAt: '2026-09-23T14:00:00.000Z',
      updatedAt: '2026-09-24T15:30:00.000Z',
      completedAt: '2026-09-24T15:30:00.000Z',
    },
    {
      id: 'ret_vend_1',
      number: 'RET-V/00001',
      type: 'vendor',
      status: 'approved',
      partnerId: vnd2,
      partnerName: 'RodWorks Precision Co.',
      referenceDocNumber: 'PO/00002',
      warehouseId: wh1,
      lines: [
        {
          id: uid('retl'),
          productId: pRod,
          qty: 3,
          reason: 'Defective thread cut during inspection',
          destination: 'damaged',
          inspectedQty: 3,
          disposition: 'damaged',
        },
      ],
      notes: 'Vendor RMA authorized #RMA-8841. Awaiting scheduled pickup.',
      createdAt: '2026-09-25T14:00:00.000Z',
      updatedAt: '2026-09-25T16:00:00.000Z',
    },
  ]

  return {
    users: [
      {
        id: userId,
        name: 'Alex Morgan',
        email: 'demo@stocksense.app',
        passwordHash: DEMO_HASH,
        role: 'inventory_manager',
        phone: '+1 415 555 0148',
      },
    ],
    sessionUserId: null,
    pendingOtp: null,
    warehouses: [
      {
        id: wh1,
        name: 'Main Warehouse',
        code: 'WH1',
        address: '120 Industrial Ave',
      },
      {
        id: wh2,
        name: 'Warehouse 2',
        code: 'WH2',
        address: '44 Harbor Road',
      },
    ],
    locations: [
      { id: locMain, warehouseId: wh1, name: 'Main Store', code: 'WH1/Stock', type: 'internal' },
      { id: locProd, warehouseId: wh1, name: 'Production Rack', code: 'WH1/Production', type: 'internal' },
      { id: locIn, warehouseId: wh1, name: 'Receiving', code: 'WH1/Input', type: 'internal' },
      { id: locOut, warehouseId: wh1, name: 'Shipping Dock', code: 'WH1/Output', type: 'internal' },
      { id: locWh2, warehouseId: wh2, name: 'WH2 Stock', code: 'WH2/Stock', type: 'internal' },
      { id: locVendor, warehouseId: null, name: 'Vendors', code: 'Partner/Vendors', type: 'vendor' },
      { id: locCustomer, warehouseId: null, name: 'Customers', code: 'Partner/Customers', type: 'customer' },
      { id: locLoss, warehouseId: null, name: 'Inventory Loss', code: 'Virtual/Loss', type: 'inventory_loss' },
    ],
    categories: [
      { id: catRaw, name: 'Raw Materials' },
      { id: catFin, name: 'Finished Goods' },
      { id: catComp, name: 'Components' },
    ],
    products: [
      {
        id: pSteel,
        name: 'Steel',
        sku: 'ST-KG-001',
        categoryId: catRaw,
        uom: 'kg',
        description: 'Bulk steel for production',
        costPrice: 28,
        salesPrice: 45,
        primaryVendorId: vnd1,
      },
      {
        id: pRod,
        name: 'Steel Rods',
        sku: 'ST-ROD-050',
        categoryId: catRaw,
        uom: 'Units',
        description: '10mm steel rods',
        costPrice: 14,
        salesPrice: 24,
        primaryVendorId: vnd2,
      },
      {
        id: pChair,
        name: 'Office Chair',
        sku: 'FG-CH-010',
        categoryId: catFin,
        uom: 'Units',
        description: 'Ergonomic office chair',
        costPrice: 85,
        salesPrice: 175,
        primaryVendorId: vnd3,
      },
      {
        id: pFrame,
        name: 'Steel Frame',
        sku: 'CP-FR-020',
        categoryId: catComp,
        uom: 'Units',
        description: 'Welded steel frame',
        costPrice: 42,
        salesPrice: 79,
        primaryVendorId: vnd1,
      },
    ],
    reorderRules: [
      { id: uid('rr'), productId: pSteel, locationId: locProd, minQty: 20, maxQty: 200 },
      { id: uid('rr'), productId: pChair, locationId: locMain, minQty: 5, maxQty: 40 },
      { id: uid('rr'), productId: pRod, locationId: locMain, minQty: 15, maxQty: 100 },
    ],
    quants: [
      { id: uid('q'), productId: pSteel, locationId: locProd, qty: 77 },
      { id: uid('q'), productId: pRod, locationId: locMain, qty: 12 },
      { id: uid('q'), productId: pChair, locationId: locMain, qty: 8 },
      { id: uid('q'), productId: pFrame, locationId: locMain, qty: 30 },
    ],
    documents: [
      {
        id: rec1,
        number: 'WH/IN/00001',
        type: 'receipt',
        status: 'done',
        warehouseId: wh1,
        sourceLocationId: locVendor,
        destLocationId: locMain,
        partnerName: 'MetalsPlus Industries',
        scheduledDate: '2026-09-20',
        notes: 'Receive 100 kg Steel (PO/00001)',
        lines: [{ id: uid('ln'), productId: pSteel, qty: 100 }],
        createdAt: '2026-09-20T09:00:00.000Z',
        validatedAt: '2026-09-20T09:12:00.000Z',
        pickDone: false,
        packDone: false,
        createdBy: userId,
      },
      {
        id: int1,
        number: 'WH/INT/00001',
        type: 'internal',
        status: 'done',
        warehouseId: wh1,
        sourceLocationId: locMain,
        destLocationId: locProd,
        partnerName: '',
        scheduledDate: '2026-09-21',
        notes: 'Main Store → Production Rack',
        lines: [{ id: uid('ln'), productId: pSteel, qty: 100 }],
        createdAt: '2026-09-21T10:00:00.000Z',
        validatedAt: '2026-09-21T10:20:00.000Z',
        pickDone: false,
        packDone: false,
        createdBy: userId,
      },
      {
        id: del1,
        number: 'WH/OUT/00001',
        type: 'delivery',
        status: 'done',
        warehouseId: wh1,
        sourceLocationId: locProd,
        destLocationId: locCustomer,
        partnerName: 'Northwind Manufacturing',
        scheduledDate: '2026-09-22',
        notes: 'Deliver 20 kg steel (SO/00001)',
        lines: [{ id: uid('ln'), productId: pSteel, qty: 20 }],
        createdAt: '2026-09-22T11:00:00.000Z',
        validatedAt: '2026-09-22T14:00:00.000Z',
        pickDone: true,
        packDone: true,
        createdBy: userId,
      },
      {
        id: adj1,
        number: 'WH/ADJ/00001',
        type: 'adjustment',
        status: 'done',
        warehouseId: wh1,
        sourceLocationId: locProd,
        destLocationId: locLoss,
        partnerName: '',
        scheduledDate: '2026-09-23',
        notes: '3 kg steel damaged',
        lines: [{ id: uid('ln'), productId: pSteel, qty: 3, countedQty: 77 }],
        createdAt: '2026-09-23T16:00:00.000Z',
        validatedAt: '2026-09-23T16:10:00.000Z',
        pickDone: false,
        packDone: false,
        createdBy: userId,
      },
      {
        id: uid('doc'),
        number: 'WH/IN/00002',
        type: 'receipt',
        status: 'ready',
        warehouseId: wh1,
        sourceLocationId: locVendor,
        destLocationId: locIn,
        partnerName: 'RodWorks Precision Co.',
        scheduledDate: '2026-09-26',
        notes: 'Pending inbound rods (PO/00002)',
        lines: [{ id: uid('ln'), productId: pRod, qty: 50 }],
        createdAt: '2026-09-25T08:00:00.000Z',
        pickDone: false,
        packDone: false,
        createdBy: userId,
      },
      {
        id: uid('doc'),
        number: 'WH/OUT/00002',
        type: 'delivery',
        status: 'waiting',
        warehouseId: wh1,
        sourceLocationId: locMain,
        destLocationId: locCustomer,
        partnerName: 'City Office Fitouts',
        scheduledDate: '2026-09-27',
        notes: 'Waiting on chair availability',
        lines: [{ id: uid('ln'), productId: pChair, qty: 12 }],
        createdAt: '2026-09-25T09:30:00.000Z',
        pickDone: false,
        packDone: false,
        createdBy: userId,
      },
      {
        id: uid('doc'),
        number: 'WH/INT/00002',
        type: 'internal',
        status: 'ready',
        warehouseId: wh1,
        sourceLocationId: locMain,
        destLocationId: locWh2,
        partnerName: '',
        scheduledDate: '2026-09-26',
        notes: 'Warehouse 1 → Warehouse 2',
        lines: [{ id: uid('ln'), productId: pFrame, qty: 10 }],
        createdAt: '2026-09-25T12:00:00.000Z',
        pickDone: false,
        packDone: false,
        createdBy: userId,
      },
    ],
    ledger: [
      {
        id: uid('led'),
        date: '2026-09-20T09:12:00.000Z',
        productId: pSteel,
        fromLocationId: locVendor,
        toLocationId: locMain,
        qty: 100,
        type: 'receipt',
        documentId: rec1,
        documentNumber: 'WH/IN/00001',
        note: 'Receive 100 kg Steel',
        userId,
        unitCost: 28,
      },
      {
        id: uid('led'),
        date: '2026-09-21T10:20:00.000Z',
        productId: pSteel,
        fromLocationId: locMain,
        toLocationId: locProd,
        qty: 100,
        type: 'internal',
        documentId: int1,
        documentNumber: 'WH/INT/00001',
        note: 'Main Store → Production Rack',
        userId,
        unitCost: 28,
      },
      {
        id: uid('led'),
        date: '2026-09-22T14:00:00.000Z',
        productId: pSteel,
        fromLocationId: locProd,
        toLocationId: locCustomer,
        qty: 20,
        type: 'delivery',
        documentId: del1,
        documentNumber: 'WH/OUT/00001',
        note: 'Deliver 20 kg steel',
        userId,
        unitCost: 28,
      },
      {
        id: uid('led'),
        date: '2026-09-23T16:10:00.000Z',
        productId: pSteel,
        fromLocationId: locProd,
        toLocationId: locLoss,
        qty: 3,
        type: 'adjustment',
        documentId: adj1,
        documentNumber: 'WH/ADJ/00001',
        note: '3 kg steel damaged',
        userId,
        unitCost: 28,
      },
      {
        id: uid('led'),
        date: '2026-09-24T15:30:00.000Z',
        productId: pSteel,
        fromLocationId: locCustomer,
        toLocationId: locMain,
        qty: 2,
        type: 'return',
        documentId: null,
        documentNumber: 'RET-C/00001',
        note: 'Customer return restock',
        userId,
        unitCost: 28,
      },
    ],
    sequences: {
      receipt: 2,
      delivery: 2,
      internal: 2,
      adjustment: 1,
      po: 4,
      so: 4,
      ret_cust: 1,
      ret_vend: 1,
    },
    vendors,
    customers,
    purchaseOrders,
    salesOrders,
    reservations,
    returnOrders,

    // ── Warehouse Operations Addon v3 seed data ──────────────

    barcodeRecords: [
      { id: uid('bc'), barcode: 'SS-PRD-STEEL001', format: 'CODE128', entityType: 'product', entityId: pSteel, createdAt: '2026-09-01T08:00:00.000Z' },
      { id: uid('bc'), barcode: 'SS-PRD-ROD00001', format: 'CODE128', entityType: 'product', entityId: pRod, createdAt: '2026-09-01T08:00:00.000Z' },
      { id: uid('bc'), barcode: 'SS-PRD-CHAIR001', format: 'CODE128', entityType: 'product', entityId: pChair, createdAt: '2026-09-01T08:00:00.000Z' },
      { id: uid('bc'), barcode: 'SS-PRD-FRAME001', format: 'CODE128', entityType: 'product', entityId: pFrame, createdAt: '2026-09-01T08:00:00.000Z' },
      { id: uid('bc'), barcode: 'SS-LOC-MAINST01', format: 'CODE128', entityType: 'location', entityId: locMain, createdAt: '2026-09-01T08:00:00.000Z' },
      { id: uid('bc'), barcode: 'SS-LOC-PRODRK01', format: 'CODE128', entityType: 'location', entityId: locProd, createdAt: '2026-09-01T08:00:00.000Z' },
      { id: uid('bc'), barcode: 'SS-WH-MAIN0001', format: 'CODE128', entityType: 'warehouse', entityId: wh1, createdAt: '2026-09-01T08:00:00.000Z' },
    ] as BarcodeRecord[],

    productExtensions: [
      { productId: pSteel, trackingType: 'lot' as const, hasVariants: false, attributes: [], expiryWarningDays: 0, rotationMethod: 'FIFO' as const },
      { productId: pRod, trackingType: 'lot' as const, hasVariants: false, attributes: [], expiryWarningDays: 0, rotationMethod: 'FIFO' as const },
      { productId: pChair, trackingType: 'serial' as const, hasVariants: true, attributes: [{ id: uid('attr'), name: 'Color', values: ['Black', 'Gray', 'White'] }], expiryWarningDays: 0, rotationMethod: 'FIFO' as const },
      { productId: pFrame, trackingType: 'none' as const, hasVariants: false, attributes: [], expiryWarningDays: 0, rotationMethod: 'FIFO' as const },
    ],

    productVariants: [
      { id: 'var_chair_black', productId: pChair, variantSku: 'FG-CH-010-BLK', barcode: 'SS-VAR-CH010BLK', attributeValues: { Color: 'Black' }, costPrice: 85, salesPrice: 175, active: true, createdAt: '2026-09-01T08:00:00.000Z' },
      { id: 'var_chair_gray', productId: pChair, variantSku: 'FG-CH-010-GRY', barcode: 'SS-VAR-CH010GRY', attributeValues: { Color: 'Gray' }, costPrice: 85, salesPrice: 170, active: true, createdAt: '2026-09-01T08:00:00.000Z' },
      { id: 'var_chair_white', productId: pChair, variantSku: 'FG-CH-010-WHT', barcode: 'SS-VAR-CH010WHT', attributeValues: { Color: 'White' }, costPrice: 88, salesPrice: 180, active: false, createdAt: '2026-09-01T08:00:00.000Z' },
    ] as ProductVariant[],

    lots: [
      { id: 'lot_steel_001', lotNumber: 'LOT-STEEL-001', productId: pSteel, qty: 40, locationId: locProd, warehouseId: wh1, receivedDate: '2026-09-20', receiptDocId: rec1, notes: 'Batch 1 from MetalsPlus', createdAt: '2026-09-20T09:12:00.000Z' },
      { id: 'lot_steel_002', lotNumber: 'LOT-STEEL-002', productId: pSteel, qty: 37, locationId: locProd, warehouseId: wh1, receivedDate: '2026-09-20', receiptDocId: rec1, notes: 'Batch 2 from MetalsPlus', createdAt: '2026-09-20T09:12:00.000Z' },
      { id: 'lot_rod_001', lotNumber: 'LOT-ROD-001', productId: pRod, qty: 12, locationId: locMain, warehouseId: wh1, manufacturingDate: '2026-08-15', expiryDate: '2027-08-15', receivedDate: '2026-09-24', notes: 'Partial receipt PO/00002', createdAt: '2026-09-24T11:00:00.000Z' },
    ] as Lot[],

    serials: [
      { id: 'sn_chair_001', serial: 'SN-CH-0001', productId: pChair, variantId: 'var_chair_black', status: 'in_stock', locationId: locMain, warehouseId: wh1, history: [], createdAt: '2026-09-20T10:00:00.000Z' },
      { id: 'sn_chair_002', serial: 'SN-CH-0002', productId: pChair, variantId: 'var_chair_black', status: 'in_stock', locationId: locMain, warehouseId: wh1, history: [], createdAt: '2026-09-20T10:00:00.000Z' },
      { id: 'sn_chair_003', serial: 'SN-CH-0003', productId: pChair, variantId: 'var_chair_gray', status: 'reserved', locationId: locMain, warehouseId: wh1, history: [], createdAt: '2026-09-20T10:00:00.000Z' },
      { id: 'sn_chair_004', serial: 'SN-CH-0004', productId: pChair, variantId: 'var_chair_gray', status: 'delivered', locationId: locMain, warehouseId: wh1, deliveryDocId: del1, customerId: cust1, history: [], createdAt: '2026-09-20T10:00:00.000Z' },
    ] as SerialNumber[],

    warehouseZones: [
      { id: 'zone_wh1_receiving', warehouseId: wh1, name: 'Receiving', code: 'WH1/RCV', type: 'receiving', active: true, notes: 'Inbound goods area' },
      { id: 'zone_wh1_storage', warehouseId: wh1, name: 'Main Storage', code: 'WH1/STG', type: 'storage', active: true, notes: 'Primary storage area' },
      { id: 'zone_wh1_picking', warehouseId: wh1, name: 'Picking Area', code: 'WH1/PCK', type: 'picking', active: true, notes: 'Pick face zone' },
      { id: 'zone_wh1_packing', warehouseId: wh1, name: 'Packing Station', code: 'WH1/PKG', type: 'packing', active: true, notes: 'Box and seal area' },
      { id: 'zone_wh1_shipping', warehouseId: wh1, name: 'Shipping Dock', code: 'WH1/SHP', type: 'shipping', active: true, notes: 'Outbound dispatch dock' },
      { id: 'zone_wh1_qc', warehouseId: wh1, name: 'Quality Control', code: 'WH1/QC', type: 'quality_control', active: true, notes: 'Inspection area' },
      { id: 'zone_wh2_storage', warehouseId: wh2, name: 'WH2 Storage', code: 'WH2/STG', type: 'storage', active: true, notes: '' },
    ] as WarehouseZone[],

    locationExtensions: [
      { locationId: locIn, zoneId: 'zone_wh1_receiving', capacity: 500, binCode: 'A1', active: true },
      { locationId: locMain, zoneId: 'zone_wh1_storage', capacity: 1000, binCode: 'B1', active: true },
      { locationId: locProd, zoneId: 'zone_wh1_picking', capacity: 300, binCode: 'C1', active: true },
      { locationId: locOut, zoneId: 'zone_wh1_shipping', capacity: 200, binCode: 'D1', active: true },
      { locationId: locWh2, zoneId: 'zone_wh2_storage', capacity: 800, binCode: 'E1', active: true },
    ] as LocationExtension[],

    putawayRules: [
      { id: uid('pa'), warehouseId: wh1, zoneId: 'zone_wh1_storage', locationId: locMain, categoryId: 'cat_raw', priority: 10, active: true, notes: 'Raw materials → Main Store', createdAt: '2026-09-01T08:00:00.000Z' },
      { id: uid('pa'), warehouseId: wh1, zoneId: 'zone_wh1_storage', locationId: locMain, categoryId: 'cat_fin', priority: 20, active: true, notes: 'Finished goods → Main Store', createdAt: '2026-09-01T08:00:00.000Z' },
      { id: uid('pa'), warehouseId: wh1, zoneId: 'zone_wh1_picking', locationId: locProd, categoryId: 'cat_comp', priority: 30, active: true, notes: 'Components → Production Rack', createdAt: '2026-09-01T08:00:00.000Z' },
    ] as PutawayRule[],

    cycleCounts: [
      {
        id: 'cc_001',
        number: 'CC/00001',
        warehouseId: wh1,
        locationId: locMain,
        assignedUserId: userId,
        scheduledDate: '2026-09-26',
        status: 'review',
        notes: 'Monthly cycle count — Main Store',
        lines: [
          { id: uid('ccl'), productId: pRod, expected: 12, counted: 11, variance: -1 },
          { id: uid('ccl'), productId: pChair, expected: 8, counted: 8, variance: 0 },
          { id: uid('ccl'), productId: pFrame, expected: 30, counted: 32, variance: 2 },
        ],
        createdAt: '2026-09-25T08:00:00.000Z',
        createdBy: userId,
      },
    ] as CycleCount[],

    pickingOrders: [
      {
        id: 'pick_001',
        number: 'PICK/00001',
        method: 'single',
        status: 'in_progress',
        warehouseId: wh1,
        documentIds: [del1],
        lines: [
          {
            id: uid('pkl'),
            documentId: del1,
            productId: pSteel,
            qtyTodo: 20,
            qtyDone: 20,
            sourceLocationId: locProd,
            confirmed: true,
          },
        ],
        assignedUserId: userId,
        scheduledDate: '2026-09-22',
        notes: 'Pick for delivery WH/OUT/00001',
        createdAt: '2026-09-22T10:00:00.000Z',
      },
    ] as PickingOrder[],

    packages: [
      {
        id: 'pkg_001',
        packageNumber: 'PKG-0001',
        deliveryDocId: del1,
        type: 'Box',
        weight: 20,
        length: 60,
        width: 40,
        height: 30,
        status: 'sealed',
        productLines: [{ productId: pSteel, qty: 20 }],
        createdAt: '2026-09-22T12:00:00.000Z',
        sealedAt: '2026-09-22T13:30:00.000Z',
      },
    ] as Package[],

    shipments: [
      {
        id: 'ship_001',
        number: 'SHIP/00001',
        deliveryDocId: del1,
        carrier: 'FedEx',
        trackingNumber: 'FX-9841023847',
        shippingMethod: 'Ground',
        shippedDate: '2026-09-22',
        estimatedDelivery: '2026-09-24',
        status: 'delivered',
        notes: 'Delivered on time',
        createdAt: '2026-09-22T14:00:00.000Z',
        updatedAt: '2026-09-24T16:00:00.000Z',
      },
    ] as Shipment[],
  }
}
